INSERT INTO INCOME (ID, CHAT_ID, INCOME) VALUES (DEFAULT, 2, 1900);
INSERT INTO INCOME (ID, CHAT_ID, INCOME) VALUES (DEFAULT, 555,555);
INSERT INTO SPEND (ID, CHAT_ID, SPEND) VALUES (DEFAULT, 2, 1500);
INSERT INTO SPEND (ID, CHAT_ID, SPEND) VALUES (DEFAULT, 555, 222);
